function affichage_zernike(handles,zernike)
[string, errmsg] = sprintf('%2.2g',zernike(1));
set(handles.valeur_zernike_01,'string',string);
[string, errmsg] = sprintf('%2.2g',zernike(2));
set(handles.valeur_zernike_02,'string',string);
[string, errmsg] = sprintf('%2.2g',zernike(3));
set(handles.valeur_zernike_03,'string',string);
[string, errmsg] = sprintf('%2.2g',zernike(4));
set(handles.valeur_zernike_04,'string',string);
[string, errmsg] = sprintf('%2.2g',zernike(5));
set(handles.valeur_zernike_05,'string',string);
[string, errmsg] = sprintf('%2.2g',zernike(6));
set(handles.valeur_zernike_06,'string',string);
[string, errmsg] = sprintf('%2.2g',zernike(7));
set(handles.valeur_zernike_07,'string',string);
[string, errmsg] = sprintf('%2.2g',zernike(8));
set(handles.valeur_zernike_08,'string',string);
[string, errmsg] = sprintf('%2.2g',zernike(9));
set(handles.valeur_zernike_09,'string',string);
[string, errmsg] = sprintf('%2.2g',zernike(10));
set(handles.valeur_zernike_10,'string',string);
[string, errmsg] = sprintf('%2.2g',zernike(11));
set(handles.valeur_zernike_11,'string',string);
[string, errmsg] = sprintf('%2.2g',zernike(12));
set(handles.valeur_zernike_12,'string',string);
[string, errmsg] = sprintf('%2.2g',zernike(13));
set(handles.valeur_zernike_13,'string',string);
[string, errmsg] = sprintf('%2.2g',zernike(14));
set(handles.valeur_zernike_14,'string',string);
[string, errmsg] = sprintf('%2.2g',zernike(15));
set(handles.valeur_zernike_15,'string',string);
[string, errmsg] = sprintf('%2.2g',zernike(16));
set(handles.valeur_zernike_16,'string',string);
[string, errmsg] = sprintf('%2.2g',zernike(17));
set(handles.valeur_zernike_17,'string',string);
[string, errmsg] = sprintf('%2.2g',zernike(18));
set(handles.valeur_zernike_18,'string',string);
[string, errmsg] = sprintf('%2.2g',zernike(19));
set(handles.valeur_zernike_19,'string',string);
[string, errmsg] = sprintf('%2.2g',zernike(20));
set(handles.valeur_zernike_20,'string',string);
[string, errmsg] = sprintf('%2.2g',zernike(21));
set(handles.valeur_zernike_21,'string',string);
[string, errmsg] = sprintf('%2.2g',zernike(22));
set(handles.valeur_zernike_22,'string',string);
[string, errmsg] = sprintf('%2.2g',zernike(23));
set(handles.valeur_zernike_23,'string',string);
[string, errmsg] = sprintf('%2.2g',zernike(24));
set(handles.valeur_zernike_24,'string',string);
[string, errmsg] = sprintf('%2.2g',zernike(25));
set(handles.valeur_zernike_25,'string',string);
[string, errmsg] = sprintf('%2.2g',zernike(26));
set(handles.valeur_zernike_26,'string',string);
[string, errmsg] = sprintf('%2.2g',zernike(27));
set(handles.valeur_zernike_27,'string',string);
[string, errmsg] = sprintf('%2.2g',zernike(28));
set(handles.valeur_zernike_28,'string',string);
[string, errmsg] = sprintf('%2.2g',zernike(29));
set(handles.valeur_zernike_29,'string',string);
[string, errmsg] = sprintf('%2.2g',zernike(30));
set(handles.valeur_zernike_30,'string',string);
[string, errmsg] = sprintf('%2.2g',zernike(31));
set(handles.valeur_zernike_31,'string',string);
[string, errmsg] = sprintf('%2.2g',zernike(32));
set(handles.valeur_zernike_32,'string',string);
[string, errmsg] = sprintf('%2.2g',zernike(33));
set(handles.valeur_zernike_33,'string',string);
[string, errmsg] = sprintf('%2.2g',zernike(34));
set(handles.valeur_zernike_34,'string',string);
[string, errmsg] = sprintf('%2.2g',zernike(35));
set(handles.valeur_zernike_35,'string',string);
[string, errmsg] = sprintf('%2.2g',zernike(36));
set(handles.valeur_zernike_36,'string',string);
