function affichage_seidel(handles, zernike);
seidel=conversion_zernike2seidel(zernike);
[string, errmsg] = sprintf('%2.3g',seidel(1,1));
set(handles.valeur_seidel_ampltilt,'string',string);
[string, errmsg] = sprintf('%2.3g',seidel(1,2));
set(handles.valeur_seidel_angltilt,'string',string);
[string, errmsg] = sprintf('%2.3g',seidel(2,1));
set(handles.valeur_seidel_ampldefoc,'string',string);
[string, errmsg] = sprintf('%2.3g',seidel(5,1));
set(handles.valeur_seidel_amplabspher,'string',string);
[string, errmsg] = sprintf('%2.3g',seidel(3,1));
set(handles.valeur_seidel_amplastig,'string',string);
[string, errmsg] = sprintf('%2.3g',seidel(3,2));
set(handles.valeur_seidel_anglastig,'string',string);
[string, errmsg] = sprintf('%2.3g',seidel(4,1));
set(handles.valeur_seidel_amplcoma,'string',string);
[string, errmsg] = sprintf('%2.3g',seidel(4,2));
set(handles.valeur_seidel_anglcoma,'string',string);